### ISSUE TITLE
In some areas, noise will be better after the new runway is built. Is that correct?

### ISSUE THREAD

**Issue by adieyal** [Code4SA/cpt-noise#9]

**Comment by longhotsummer** [comment]
We're looking into the veracity of this.

**Comment by longhotsummer** [comment]
This is correct. This is a runway re-alignment, not an addition. So it will improve. See http://www.srk.co.za/en/za-cape-town-international-airport-runway-re-alignment-eia

I'm going to change our wording.

**Comment by longhotsummer** [comment]
Fixed by 431ba30d
